Add missing CommandOptionTypes
nyxx-discord/nyxx_interactions pull request #4
Opened 2021-10-28 23:55 UTC by HarryET

2021-10-29 20:37 UTC, l7ssha requested changes

2021-10-29 20:37 UTC, l7ssha commented on lib/src/models/CommandOption.dart
> +	static const number = const CommandOptionType(10);
indentation

2021-12-23 10:59 UTC, l7ssha approved these changes

2021-12-23 10:59 UTC, abitofevrything approved these changes

2021-12-27 00:25 UTC, l7ssha approved these changes

2021-12-27 00:25 UTC, merged