Allow handlers on different nesting layers, closes nyxx#233
nyxx-discord/nyxx_interactions pull request #5
Opened 2021-11-01 23:50 UTC by abitofevrything

# Description

Previously handlers could not be registered for both subcommands and sub-subcommands because of the way preventing root handlers on slash commands with subcommands was implemented. This PR reworks that system to allow both subcommands and sub-subcommands to have handlers, while still preventing slash commands with subcommands having roor handlers.

Also added .gitignore since it was missing, it is the same as [nyxx](https://github.com/nyxx-discord/nyxx/blob/dev/.gitignore).

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] Ran `dartanalyzer --options analysis_options.yaml .`
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-11-01 23:51 UTC, abitofevrything commented
Also closes #3.

2021-11-02 13:15 UTC, l7ssha requested changes
One small comment otherwise looks good

2021-11-02 13:15 UTC, l7ssha commented on .gitignore
> +old.*
no new line at the end of file

2021-11-02 13:18 UTC, abitofevrything commented
Newline has been added.

2021-11-02 15:05 UTC, l7ssha approved these changes
Thanks, I will marge it later this day and 2.1.1 version will be pushed also

2021-11-02 16:39 UTC, merged