Bug/differentiate guild handlers
nyxx-discord/nyxx_interactions pull request #50
Opened 2022-06-05 09:20 UTC by abitofevrything

# Description

Closes #49 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] Ran `dart analyze` or `make analyze` and fixed all issues
- [x] Ran `dart format --set-exit-if-changed -l 160 ./lib` or `make format` and fixed all issues
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my changes haven't lowered code coverage

2022-06-08 20:32 UTC, l7ssha submitted a review, later dismissed

2022-06-09 06:35 UTC, Rapougnac requested changes
Smol typo

2022-06-09 06:35 UTC, Rapougnac commented on lib/src/models/slash_command_permission.dart
> +  /// Whether these overrideas are global across all commands in a guild.
```suggestion
  /// Whether these overrides are global across all commands in a guild.
```

2022-06-20 08:59 UTC, l7ssha approved these changes

2022-06-20 11:59 UTC, merged